### ISSUE TITLE
Flying speed calculated incorrectly

### ISSUE THREAD

**Issue by KJones94** [KJones94/IC-Combiner#12]
Example: Albatross/Dragonfly

**Comment by WillSO93** [comment]
This might just be how your app detects the speed from the flyers.
The dragonfly is a special case and has all of it's airspeed assigned to it's wings (and not it's torso as in other cases).

**Comment by KJones94** [comment]
I never knew that I'll check that out

**Comment by KJones94** [comment]
It is mostly correct now. I'll look at it more closely for the outliers when I take a look at stats as a whole.
