### ISSUE TITLE
New body parts view

### ISSUE THREAD

**Issue by KJones94** [KJones94/IC-Combiner#22]
View for body parts is tough to use and needs an improvement

**Comment by brandon227** [comment]
Unsure how hard this would be....but what if you had a generic silhouette or outline of a creature that had all the body parts (e.g. outline of a wolf with lobster claws and wings), with text fields on top of or next to each body part that would say "giraffe" and "Rattlesnake" or "x" if not included. Would be easy to visualize.

**Comment by KJones94** [comment]
Added.
