### ISSUE TITLE
Coyote/Moose displays double elec cost.

### ISSUE THREAD

**Issue by WillSO93** [KJones94/IC-Combiner#83]
Coyote with Moose head displays an electricity cost of 122 when it infact costs 61 electricity.

**Comment by KJones94** [comment]
Looks like a bug

**Comment by KJones94** [comment]
It looks like this has to do with DT_HornNegateFull and DT_HornNegateArmour. I need to learn the difference before I can fix it.

**Comment by KJones94** [comment]
Horns is using DT_HornNegateArmour so that is reflected in the app now.
